# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_djohnsonsb <- function(x, mu, theta, tau, logprob = FALSE) {
    .Call('_unitquantreg_cpp_djohnsonsb', PACKAGE = 'unitquantreg', x, mu, theta, tau, logprob)
}

cpp_pjohnsonsb <- function(x, mu, theta, tau, lowertail = TRUE, logprob = FALSE) {
    .Call('_unitquantreg_cpp_pjohnsonsb', PACKAGE = 'unitquantreg', x, mu, theta, tau, lowertail, logprob)
}

cpp_qjohnsonsb <- function(x, mu, theta, tau, lowertail = TRUE, logprob = FALSE) {
    .Call('_unitquantreg_cpp_qjohnsonsb', PACKAGE = 'unitquantreg', x, mu, theta, tau, lowertail, logprob)
}

cpp_loglikejohnsonsb <- function(x, lnx, n, mu, theta, tau) {
    .Call('_unitquantreg_cpp_loglikejohnsonsb', PACKAGE = 'unitquantreg', x, lnx, n, mu, theta, tau)
}

cpp_gradientjohnsonsb <- function(n, x, U, dmu_deta, dtheta_dzeta, mu, theta, tau) {
    .Call('_unitquantreg_cpp_gradientjohnsonsb', PACKAGE = 'unitquantreg', n, x, U, dmu_deta, dtheta_dzeta, mu, theta, tau)
}

cpp_hessianjohnsonsb <- function(n, x, H, mu, theta, tau) {
    .Call('_unitquantreg_cpp_hessianjohnsonsb', PACKAGE = 'unitquantreg', n, x, H, mu, theta, tau)
}

cpp_dkum <- function(x, mu, theta, tau, logprob = FALSE) {
    .Call('_unitquantreg_cpp_dkum', PACKAGE = 'unitquantreg', x, mu, theta, tau, logprob)
}

cpp_pkum <- function(x, mu, theta, tau, lowertail = TRUE, logprob = FALSE) {
    .Call('_unitquantreg_cpp_pkum', PACKAGE = 'unitquantreg', x, mu, theta, tau, lowertail, logprob)
}

cpp_qkum <- function(x, mu, theta, tau, lowertail = TRUE, logprob = FALSE) {
    .Call('_unitquantreg_cpp_qkum', PACKAGE = 'unitquantreg', x, mu, theta, tau, lowertail, logprob)
}

cpp_loglikekum <- function(x, lnx, n, mu, theta, tau) {
    .Call('_unitquantreg_cpp_loglikekum', PACKAGE = 'unitquantreg', x, lnx, n, mu, theta, tau)
}

cpp_gradientkum <- function(n, x, U, dmu_deta, dtheta_dzeta, mu, theta, tau) {
    .Call('_unitquantreg_cpp_gradientkum', PACKAGE = 'unitquantreg', n, x, U, dmu_deta, dtheta_dzeta, mu, theta, tau)
}

cpp_hessiankum <- function(n, x, H, mu, theta, tau) {
    .Call('_unitquantreg_cpp_hessiankum', PACKAGE = 'unitquantreg', n, x, H, mu, theta, tau)
}

cpp_dleeg <- function(x, mu, theta, tau, logprob = FALSE) {
    .Call('_unitquantreg_cpp_dleeg', PACKAGE = 'unitquantreg', x, mu, theta, tau, logprob)
}

cpp_pleeg <- function(x, mu, theta, tau, lowertail = TRUE, logprob = FALSE) {
    .Call('_unitquantreg_cpp_pleeg', PACKAGE = 'unitquantreg', x, mu, theta, tau, lowertail, logprob)
}

cpp_qleeg <- function(x, mu, theta, tau, lowertail = TRUE, logprob = FALSE) {
    .Call('_unitquantreg_cpp_qleeg', PACKAGE = 'unitquantreg', x, mu, theta, tau, lowertail, logprob)
}

cpp_loglikeleeg <- function(x, lnx, n, mu, theta, tau) {
    .Call('_unitquantreg_cpp_loglikeleeg', PACKAGE = 'unitquantreg', x, lnx, n, mu, theta, tau)
}

cpp_gradientleeg <- function(n, x, U, dmu_deta, dtheta_dzeta, mu, theta, tau) {
    .Call('_unitquantreg_cpp_gradientleeg', PACKAGE = 'unitquantreg', n, x, U, dmu_deta, dtheta_dzeta, mu, theta, tau)
}

cpp_hessianleeg <- function(n, x, H, mu, theta, tau) {
    .Call('_unitquantreg_cpp_hessianleeg', PACKAGE = 'unitquantreg', n, x, H, mu, theta, tau)
}

cpp_dubs <- function(x, mu, theta, tau, logprob = FALSE) {
    .Call('_unitquantreg_cpp_dubs', PACKAGE = 'unitquantreg', x, mu, theta, tau, logprob)
}

cpp_pubs <- function(x, mu, theta, tau, lowertail = TRUE, logprob = FALSE) {
    .Call('_unitquantreg_cpp_pubs', PACKAGE = 'unitquantreg', x, mu, theta, tau, lowertail, logprob)
}

cpp_qubs <- function(x, mu, theta, tau, lowertail = TRUE, logprob = FALSE) {
    .Call('_unitquantreg_cpp_qubs', PACKAGE = 'unitquantreg', x, mu, theta, tau, lowertail, logprob)
}

cpp_loglikeubs <- function(x, lnx, n, mu, theta, tau) {
    .Call('_unitquantreg_cpp_loglikeubs', PACKAGE = 'unitquantreg', x, lnx, n, mu, theta, tau)
}

cpp_gradientubs <- function(n, x, U, dmu_deta, dtheta_dzeta, mu, theta, tau) {
    .Call('_unitquantreg_cpp_gradientubs', PACKAGE = 'unitquantreg', n, x, U, dmu_deta, dtheta_dzeta, mu, theta, tau)
}

cpp_hessianubs <- function(n, x, H, mu, theta, tau) {
    .Call('_unitquantreg_cpp_hessianubs', PACKAGE = 'unitquantreg', n, x, H, mu, theta, tau)
}

cpp_duburrxii <- function(x, mu, theta, tau, logprob = FALSE) {
    .Call('_unitquantreg_cpp_duburrxii', PACKAGE = 'unitquantreg', x, mu, theta, tau, logprob)
}

cpp_puburrxii <- function(x, mu, theta, tau, lowertail = TRUE, logprob = FALSE) {
    .Call('_unitquantreg_cpp_puburrxii', PACKAGE = 'unitquantreg', x, mu, theta, tau, lowertail, logprob)
}

cpp_quburrxii <- function(x, mu, theta, tau, lowertail = TRUE, logprob = FALSE) {
    .Call('_unitquantreg_cpp_quburrxii', PACKAGE = 'unitquantreg', x, mu, theta, tau, lowertail, logprob)
}

cpp_loglikeuburrxii <- function(x, lnx, n, mu, theta, tau) {
    .Call('_unitquantreg_cpp_loglikeuburrxii', PACKAGE = 'unitquantreg', x, lnx, n, mu, theta, tau)
}

cpp_gradientuburrxii <- function(n, x, U, dmu_deta, dtheta_dzeta, mu, theta, tau) {
    .Call('_unitquantreg_cpp_gradientuburrxii', PACKAGE = 'unitquantreg', n, x, U, dmu_deta, dtheta_dzeta, mu, theta, tau)
}

cpp_hessianuburrxii <- function(n, x, H, mu, theta, tau) {
    .Call('_unitquantreg_cpp_hessianuburrxii', PACKAGE = 'unitquantreg', n, x, H, mu, theta, tau)
}

cpp_duchen <- function(x, mu, theta, tau, logprob = FALSE) {
    .Call('_unitquantreg_cpp_duchen', PACKAGE = 'unitquantreg', x, mu, theta, tau, logprob)
}

cpp_puchen <- function(x, mu, theta, tau, lowertail = TRUE, logprob = FALSE) {
    .Call('_unitquantreg_cpp_puchen', PACKAGE = 'unitquantreg', x, mu, theta, tau, lowertail, logprob)
}

cpp_quchen <- function(x, mu, theta, tau, lowertail = TRUE, logprob = FALSE) {
    .Call('_unitquantreg_cpp_quchen', PACKAGE = 'unitquantreg', x, mu, theta, tau, lowertail, logprob)
}

cpp_loglikeuchen <- function(x, lnx, n, mu, theta, tau) {
    .Call('_unitquantreg_cpp_loglikeuchen', PACKAGE = 'unitquantreg', x, lnx, n, mu, theta, tau)
}

cpp_gradientuchen <- function(n, x, U, dmu_deta, dtheta_dzeta, mu, theta, tau) {
    .Call('_unitquantreg_cpp_gradientuchen', PACKAGE = 'unitquantreg', n, x, U, dmu_deta, dtheta_dzeta, mu, theta, tau)
}

cpp_hessianuchen <- function(n, x, H, mu, theta, tau) {
    .Call('_unitquantreg_cpp_hessianuchen', PACKAGE = 'unitquantreg', n, x, H, mu, theta, tau)
}

cpp_dughne <- function(x, mu, theta, tau, logprob = FALSE) {
    .Call('_unitquantreg_cpp_dughne', PACKAGE = 'unitquantreg', x, mu, theta, tau, logprob)
}

cpp_pughne <- function(x, mu, theta, tau, lowertail = TRUE, logprob = FALSE) {
    .Call('_unitquantreg_cpp_pughne', PACKAGE = 'unitquantreg', x, mu, theta, tau, lowertail, logprob)
}

cpp_qughne <- function(x, mu, theta, tau, lowertail = TRUE, logprob = FALSE) {
    .Call('_unitquantreg_cpp_qughne', PACKAGE = 'unitquantreg', x, mu, theta, tau, lowertail, logprob)
}

cpp_loglikeughne <- function(x, lnx, n, mu, theta, tau) {
    .Call('_unitquantreg_cpp_loglikeughne', PACKAGE = 'unitquantreg', x, lnx, n, mu, theta, tau)
}

cpp_gradientughne <- function(n, x, U, dmu_deta, dtheta_dzeta, mu, theta, tau) {
    .Call('_unitquantreg_cpp_gradientughne', PACKAGE = 'unitquantreg', n, x, U, dmu_deta, dtheta_dzeta, mu, theta, tau)
}

cpp_hessianughne <- function(n, x, H, mu, theta, tau) {
    .Call('_unitquantreg_cpp_hessianughne', PACKAGE = 'unitquantreg', n, x, H, mu, theta, tau)
}

cpp_dughnx <- function(x, mu, theta, tau, logprob = FALSE) {
    .Call('_unitquantreg_cpp_dughnx', PACKAGE = 'unitquantreg', x, mu, theta, tau, logprob)
}

cpp_pughnx <- function(x, mu, theta, tau, lowertail = TRUE, logprob = FALSE) {
    .Call('_unitquantreg_cpp_pughnx', PACKAGE = 'unitquantreg', x, mu, theta, tau, lowertail, logprob)
}

cpp_qughnx <- function(x, mu, theta, tau, lowertail = TRUE, logprob = FALSE) {
    .Call('_unitquantreg_cpp_qughnx', PACKAGE = 'unitquantreg', x, mu, theta, tau, lowertail, logprob)
}

cpp_loglikeughnx <- function(x, lnx, n, mu, theta, tau) {
    .Call('_unitquantreg_cpp_loglikeughnx', PACKAGE = 'unitquantreg', x, lnx, n, mu, theta, tau)
}

cpp_gradientughnx <- function(n, x, U, dmu_deta, dtheta_dzeta, mu, theta, tau) {
    .Call('_unitquantreg_cpp_gradientughnx', PACKAGE = 'unitquantreg', n, x, U, dmu_deta, dtheta_dzeta, mu, theta, tau)
}

cpp_hessianughnx <- function(n, x, H, mu, theta, tau) {
    .Call('_unitquantreg_cpp_hessianughnx', PACKAGE = 'unitquantreg', n, x, H, mu, theta, tau)
}

cpp_dugompertz <- function(x, mu, theta, tau, logprob = FALSE) {
    .Call('_unitquantreg_cpp_dugompertz', PACKAGE = 'unitquantreg', x, mu, theta, tau, logprob)
}

cpp_pugompertz <- function(x, mu, theta, tau, lowertail = TRUE, logprob = FALSE) {
    .Call('_unitquantreg_cpp_pugompertz', PACKAGE = 'unitquantreg', x, mu, theta, tau, lowertail, logprob)
}

cpp_qugompertz <- function(x, mu, theta, tau, lowertail = TRUE, logprob = FALSE) {
    .Call('_unitquantreg_cpp_qugompertz', PACKAGE = 'unitquantreg', x, mu, theta, tau, lowertail, logprob)
}

cpp_loglikeugompertz <- function(x, lnx, n, mu, theta, tau) {
    .Call('_unitquantreg_cpp_loglikeugompertz', PACKAGE = 'unitquantreg', x, lnx, n, mu, theta, tau)
}

cpp_gradientugompertz <- function(n, x, U, dmu_deta, dtheta_dzeta, mu, theta, tau) {
    .Call('_unitquantreg_cpp_gradientugompertz', PACKAGE = 'unitquantreg', n, x, U, dmu_deta, dtheta_dzeta, mu, theta, tau)
}

cpp_hessianugompertz <- function(n, x, H, mu, theta, tau) {
    .Call('_unitquantreg_cpp_hessianugompertz', PACKAGE = 'unitquantreg', n, x, H, mu, theta, tau)
}

cpp_dulogistic <- function(x, mu, theta, tau, logprob = FALSE) {
    .Call('_unitquantreg_cpp_dulogistic', PACKAGE = 'unitquantreg', x, mu, theta, tau, logprob)
}

cpp_pulogistic <- function(x, mu, theta, tau, lowertail = TRUE, logprob = FALSE) {
    .Call('_unitquantreg_cpp_pulogistic', PACKAGE = 'unitquantreg', x, mu, theta, tau, lowertail, logprob)
}

cpp_qulogistic <- function(x, mu, theta, tau, lowertail = TRUE, logprob = FALSE) {
    .Call('_unitquantreg_cpp_qulogistic', PACKAGE = 'unitquantreg', x, mu, theta, tau, lowertail, logprob)
}

cpp_loglikeulogistic <- function(x, lnx, n, mu, theta, tau) {
    .Call('_unitquantreg_cpp_loglikeulogistic', PACKAGE = 'unitquantreg', x, lnx, n, mu, theta, tau)
}

cpp_gradientulogistic <- function(n, x, U, dmu_deta, dtheta_dzeta, mu, theta, tau) {
    .Call('_unitquantreg_cpp_gradientulogistic', PACKAGE = 'unitquantreg', n, x, U, dmu_deta, dtheta_dzeta, mu, theta, tau)
}

cpp_hessianulogistic <- function(n, x, H, mu, theta, tau) {
    .Call('_unitquantreg_cpp_hessianulogistic', PACKAGE = 'unitquantreg', n, x, H, mu, theta, tau)
}

cpp_duweibull <- function(x, mu, theta, tau, logprob = FALSE) {
    .Call('_unitquantreg_cpp_duweibull', PACKAGE = 'unitquantreg', x, mu, theta, tau, logprob)
}

cpp_puweibull <- function(x, mu, theta, tau, lowertail = TRUE, logprob = FALSE) {
    .Call('_unitquantreg_cpp_puweibull', PACKAGE = 'unitquantreg', x, mu, theta, tau, lowertail, logprob)
}

cpp_quweibull <- function(x, mu, theta, tau, lowertail = TRUE, logprob = FALSE) {
    .Call('_unitquantreg_cpp_quweibull', PACKAGE = 'unitquantreg', x, mu, theta, tau, lowertail, logprob)
}

cpp_loglikeuweibull <- function(x, lnx, n, mu, theta, tau) {
    .Call('_unitquantreg_cpp_loglikeuweibull', PACKAGE = 'unitquantreg', x, lnx, n, mu, theta, tau)
}

cpp_gradientuweibull <- function(n, x, U, dmu_deta, dtheta_dzeta, mu, theta, tau) {
    .Call('_unitquantreg_cpp_gradientuweibull', PACKAGE = 'unitquantreg', n, x, U, dmu_deta, dtheta_dzeta, mu, theta, tau)
}

cpp_hessianuweibull <- function(n, x, H, mu, theta, tau) {
    .Call('_unitquantreg_cpp_hessianuweibull', PACKAGE = 'unitquantreg', n, x, H, mu, theta, tau)
}

